import type { MCQ } from "./questions";

export const pythonAssessmentQuestions: MCQ[] = [
  {
    kind: "MCQ_SINGLE",
    stem: "What does `type(42)` return?",
    choices: [
      { id: "a", label: "`'int'`", correct: false, explanation: "Close — but `type()` returns the class itself, not the string name." },
      { id: "b", label: "`<class 'int'>`", correct: true },
      { id: "c", label: "`'integer'`", correct: false },
      { id: "d", label: "`42`", correct: false },
    ],
    points: 1,
    skillSlug: "python-basics",
  },
  {
    kind: "MCQ_SINGLE",
    stem: "Which is **not** falsy in Python?",
    choices: [
      { id: "a", label: "`0`", correct: false },
      { id: "b", label: "`[]`", correct: false },
      { id: "c", label: "`\" \"` (a single space)", correct: true, explanation: "Only the *empty* string is falsy. Any non-empty string — including whitespace — is truthy." },
      { id: "d", label: "`None`", correct: false },
    ],
    points: 1,
    skillSlug: "python-types",
  },
  {
    kind: "MCQ_SINGLE",
    stem: "What does this print?\n\n```python\na = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)\n```",
    choices: [
      { id: "a", label: "`[1, 2, 3]`", correct: false, explanation: "`b = a` doesn't copy — both names point at the same list." },
      { id: "b", label: "`[1, 2, 3, 4]`", correct: true },
      { id: "c", label: "`[4]`", correct: false },
      { id: "d", label: "Error", correct: false },
    ],
    points: 2,
    skillSlug: "python-types",
  },
  {
    kind: "MCQ_SINGLE",
    stem: "How do you make `b` a real, independent copy of list `a`?",
    choices: [
      { id: "a", label: "`b = a`", correct: false, explanation: "That shares the same list." },
      { id: "b", label: "`b == a`", correct: false, explanation: "That's a comparison, not assignment." },
      { id: "c", label: "`b = a.copy()`", correct: true },
      { id: "d", label: "`b = copy(a)`", correct: false, explanation: "There's no global `copy()` function. Use `a.copy()` or `list(a)` or `a[:]`." },
    ],
    points: 1,
    skillSlug: "python-types",
  },
  {
    kind: "MCQ_SINGLE",
    stem: "How many numbers does `range(5)` produce?",
    choices: [
      { id: "a", label: "4 (0 through 3)", correct: false },
      { id: "b", label: "5 (0 through 4)", correct: true, explanation: "`range(stop)` is exclusive on the right — `range(5)` is 0, 1, 2, 3, 4." },
      { id: "c", label: "5 (1 through 5)", correct: false, explanation: "`range` starts at 0 by default." },
      { id: "d", label: "6 (0 through 5)", correct: false, explanation: "`range(stop)` excludes `stop`." },
    ],
    points: 1,
    skillSlug: "python-control-flow",
  },
  {
    kind: "MCQ_SINGLE",
    stem: "What does `continue` do inside a loop?",
    choices: [
      { id: "a", label: "Exits the loop entirely.", correct: false, explanation: "That's `break`." },
      { id: "b", label: "Skips the rest of the current iteration and moves to the next.", correct: true },
      { id: "c", label: "Restarts the loop from the beginning.", correct: false },
      { id: "d", label: "Raises an exception.", correct: false },
    ],
    points: 1,
    skillSlug: "python-control-flow",
  },
  {
    kind: "MCQ_MULTI",
    stem: "Which of these are good ways to check whether a list `users` is non-empty? (Select all idiomatic options.)",
    choices: [
      { id: "a", label: "`if users:`", correct: true, explanation: "Pythonic. Empty list is falsy, non-empty is truthy." },
      { id: "b", label: "`if len(users) > 0:`", correct: false, explanation: "Works, but not idiomatic. The pythonic form is `if users:`." },
      { id: "c", label: "`if users is not None:`", correct: false, explanation: "Different meaning — that's true even for an empty list." },
      { id: "d", label: "`if not users == []:`", correct: false, explanation: "Verbose and brittle if `users` is a different empty container." },
    ],
    points: 2,
    skillSlug: "python-control-flow",
  },
  {
    kind: "MCQ_SINGLE",
    stem: "Why is this dangerous?\n\n```python\ndef append_item(item, items=[]):\n    items.append(item)\n    return items\n```",
    choices: [
      { id: "a", label: "Default arguments aren't allowed in Python.", correct: false, explanation: "They are — just not mutable ones." },
      { id: "b", label: "The `items=[]` is evaluated once at definition time, so all calls share the same list.", correct: true },
      { id: "c", label: "`append` doesn't return anything.", correct: false, explanation: "True, but that's not the bug here — we explicitly return `items`." },
      { id: "d", label: "`items` should be in a class.", correct: false },
    ],
    points: 2,
    skillSlug: "python-functions",
  },
  {
    kind: "MCQ_SINGLE",
    stem: "What does `def double(x): x = x * 2` do to a variable `n` passed in from the caller?",
    choices: [
      { id: "a", label: "Doubles `n` in place.", correct: false, explanation: "Reassigning `x` inside doesn't change `n` outside." },
      { id: "b", label: "Returns the doubled value but doesn't change `n`.", correct: false, explanation: "There's no `return` — the function returns `None`. Either way, `n` is unchanged." },
      { id: "c", label: "Doesn't change `n`. Local `x` is reassigned but the outer `n` is untouched.", correct: true },
      { id: "d", label: "Raises an error.", correct: false },
    ],
    points: 2,
    skillSlug: "python-functions",
  },
  {
    kind: "MCQ_SINGLE",
    stem: "When should you reach for a **set** instead of a list?",
    choices: [
      { id: "a", label: "When you need to keep insertion order.", correct: false, explanation: "Sets don't preserve order in any guaranteed way." },
      { id: "b", label: "When you need duplicates.", correct: false, explanation: "Sets remove duplicates." },
      { id: "c", label: "When you need uniqueness or fast `x in s` membership tests.", correct: true },
      { id: "d", label: "When you need to access items by index.", correct: false, explanation: "Sets are unordered — no indexing." },
    ],
    points: 1,
    skillSlug: "python-collections",
  },
  {
    kind: "MCQ_SINGLE",
    stem: "What's the difference between `d[\"key\"]` and `d.get(\"key\")`?",
    choices: [
      { id: "a", label: "Nothing — they're identical.", correct: false },
      { id: "b", label: "`d[\"key\"]` raises `KeyError` if missing; `d.get(\"key\")` returns `None`.", correct: true },
      { id: "c", label: "`d.get` is faster.", correct: false, explanation: "They're effectively the same speed." },
      { id: "d", label: "`d.get` works on lists too.", correct: false, explanation: "Lists don't have `.get`." },
    ],
    points: 1,
    skillSlug: "python-collections",
  },
  {
    kind: "MCQ_MULTI",
    stem: "Which of these comprehensions correctly produce `[1, 9, 25]` from `nums = [1, 2, 3, 4, 5]`? (Select all that work.)",
    choices: [
      { id: "a", label: "`[n*n for n in nums if n % 2 == 1]`", correct: true, explanation: "Squares the odd numbers." },
      { id: "b", label: "`[n*n for n in nums if n % 2]`", correct: true, explanation: "`n % 2` is 1 (truthy) for odd, 0 (falsy) for even." },
      { id: "c", label: "`{n*n for n in nums if n % 2 == 1}`", correct: false, explanation: "Curly braces make it a set, not a list. Different result type." },
      { id: "d", label: "`[n**2 for n in nums if n % 2 == 1]`", correct: true, explanation: "`n**2` is the same as `n*n`." },
    ],
    points: 2,
    skillSlug: "python-collections",
  },
  {
    kind: "MCQ_SINGLE",
    stem: "What does this code most likely produce?\n\n```python\nfrom collections import defaultdict\n\ntotals = defaultdict(int)\nfor word in [\"a\", \"b\", \"a\", \"c\", \"a\"]:\n    totals[word] += 1\n```",
    choices: [
      { id: "a", label: "An error because the keys don't exist initially.", correct: false, explanation: "That's exactly why `defaultdict(int)` exists — missing keys default to 0." },
      { id: "b", label: "`{'a': 3, 'b': 1, 'c': 1}`", correct: true },
      { id: "c", label: "`{'a': 1, 'b': 1, 'c': 1}`", correct: false, explanation: "We're incrementing on every occurrence." },
      { id: "d", label: "`['a', 'b', 'a', 'c', 'a']`", correct: false },
    ],
    points: 2,
    skillSlug: "python-collections",
  },
  {
    kind: "MCQ_SINGLE",
    stem: "What does `if __name__ == \"__main__\":` do?",
    choices: [
      { id: "a", label: "Defines the entry point — required to run any Python file.", correct: false, explanation: "Not required — Python files run line-by-line with no entry point ceremony." },
      { id: "b", label: "Runs the indented code only when the file is executed directly, not when imported as a module.", correct: true },
      { id: "c", label: "Sets the program's name to `__main__`.", correct: false },
      { id: "d", label: "Prevents the file from being imported.", correct: false, explanation: "It can still be imported — that's the whole point. The block just doesn't run on import." },
    ],
    points: 2,
    skillSlug: "python-problem-solving",
  },
  {
    kind: "MCQ_SINGLE",
    stem: "You need to count word frequencies in a list. The pythonic one-liner is:",
    choices: [
      { id: "a", label: "Hand-roll a dict with a for loop.", correct: false, explanation: "Works, but verbose for a one-liner." },
      { id: "b", label: "`Counter(words)` from the `collections` module.", correct: true, explanation: "Designed for exactly this, plus `.most_common(n)` is built in." },
      { id: "c", label: "`set(words)`", correct: false, explanation: "Sets remove duplicates — they don't count occurrences." },
      { id: "d", label: "`dict.fromkeys(words, 1)`", correct: false, explanation: "That makes every key map to 1, regardless of how many times it appeared." },
    ],
    points: 2,
    skillSlug: "python-problem-solving",
  },
];
